#!/bin/sh
#
# This file was produced by running the Configure script. It holds all the
# definitions figured out by Configure. Should you modify one of these values,
# do not forget to propagate your changes by running "Configure -der". You may
# instead choose to run each of the .SH files by yourself, or "Configure -S".
#

# Package name      : g4conf
# Source directory  : .
# Configuration time: Mon Aug 17 12:53:46 CDT 2015
# Configured by     : root
# Target system     : linux itb2.mwt2.org 2.6.32-504.8.1.el6.x86_64 #1 smp tue jan 27 13:39:10 cst 2015 x86_64 x86_64 x86_64 gnulinux 

Author=''
Date=''
Header=''
Id=''
Locker=''
Log=''
RCSfile=''
Revision=''
Source=''
State=''
c=''
cf_by='root'
cf_time='Mon Aug 17 12:53:46 CDT 2015'
contains='grep'
d_portable='define'
eunicefix=':'
g4_gmake=''
g4_gmake_version='GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu'
g4_make=''
g4_make_version='GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu'
g4_qt_cxxflags=''
g4_qt_gl_cxxflags=''
g4_qt_gl_libs=''
g4_qt_libs=''
g4_qt_moc=''
g4_qt_version=''
g4abladata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/G4ABLA3.0'
g4base=''
g4bin=''
g4clhep_base_dir='/cvmfs/oasis.opensciencegrid.org/osg/modules/clhep/2.1.0.1/'
g4clhep_include_dir='/cvmfs/oasis.opensciencegrid.org/osg/modules/clhep/2.1.0.1//include'
g4clhep_lib='CLHEP'
g4clhep_lib_dir='/cvmfs/oasis.opensciencegrid.org/osg/modules/clhep/2.1.0.1//lib'
g4compiler='g++'
g4conf='/tmp/geant4-9.4p02/geant4.9.4.p02/.config/bin/Linux-g++'
g4data='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data'
g4debug='n'
g4elasticdata=''
g4final_install='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/'
g4gdml_xercesc_root=''
g4global='y'
g4granular='n'
g4include=''
g4includes_flag='n'
g4install='/tmp/geant4-9.4p02/geant4.9.4.p02'
g4ledata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/G4EMLOW6.19'
g4levelgammadata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/PhotonEvaporation2.1'
g4lib='/tmp/geant4-9.4p02/geant4.9.4.p02/lib'
g4lib_build_dll='n'
g4lib_build_gdml='n'
g4lib_build_shared='y'
g4lib_build_static='n'
g4lib_use_dll='n'
g4lib_use_dyn=''
g4lib_use_granular='n'
g4lib_use_shared='y'
g4lib_use_static='n'
g4make='/usr/bin/gmake'
g4make_jobs='4'
g4neutronhpcrosssections='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/G4NDL3.14'
g4neutronxsdata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/G4NEUTRONXS1.0'
g4osname='Linux'
g4piidata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/G4PII1.2'
g4radioactivedata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/RadioactiveDecay3.3'
g4realsurfacedata='/cvmfs/oasis.opensciencegrid.org/osg/modules/geant4/9.4p02/data/RealSurface1.0'
g4system='Linux-g++'
g4tmp='/tmp/geant4-9.4p02/geant4.9.4.p02/tmp'
g4ui_build_gag_session='y'
g4ui_build_qt_session='n'
g4ui_build_terminal_session='y'
g4ui_build_win32_session='n'
g4ui_build_xaw_session='n'
g4ui_build_xm_session='n'
g4ui_none='n'
g4ui_use_gag='y'
g4ui_use_qt='n'
g4ui_use_tcsh='y'
g4ui_use_terminal='y'
g4ui_use_win32='n'
g4ui_use_xaw='n'
g4ui_use_xm='n'
g4ui_xawflags=''
g4ui_xawhome=''
g4ui_xawlibs=''
g4vis_build_asciitree_driver='y'
g4vis_build_dawn_driver='n'
g4vis_build_dawnfile_driver='y'
g4vis_build_oiwin32_driver='n'
g4vis_build_oix_driver='n'
g4vis_build_openglqt_driver='n'
g4vis_build_openglwin32_driver='n'
g4vis_build_openglx_driver='n'
g4vis_build_openglxm_driver='n'
g4vis_build_raytracer_driver='y'
g4vis_build_raytracerx_driver='n'
g4vis_build_vrml_driver='n'
g4vis_build_vrmlfile_driver='y'
g4vis_oglhome=''
g4vis_oivhome=''
g4vis_use_asciitree='y'
g4vis_use_dawn='n'
g4vis_use_dawnfile='y'
g4vis_use_oiwin32='n'
g4vis_use_oix='n'
g4vis_use_openglqt='n'
g4vis_use_openglwin32='n'
g4vis_use_openglx='n'
g4vis_use_openglxm='n'
g4vis_use_raytracer='y'
g4vis_use_raytracerx='n'
g4vis_use_vrml='n'
g4vis_use_vrmlfile='y'
g4vis_xmflags=''
g4vis_xmflags=''
g4vis_xmhome=''
g4vis_xmhome=''
g4vis_xmlibs=''
g4vis_xmlibs=''
g4w_use_g3tog4='n'
g4w_use_zlib='n'
g4wlib_build_g3tog4='n'
g4wlib_build_zlib='n'
g4workdir='/tmp/geant4-9.4p02/geant4.9.4.p02'
hint='previous'
lns='/bin/ln -s'
myuname='linux itb2.mwt2.org 2.6.32-504.8.1.el6.x86_64 #1 smp tue jan 27 13:39:10 cst 2015 x86_64 x86_64 x86_64 gnulinux '
n='-n'
osname='linux'
osvers='2.6.32-504.8.1.el6.x86_64'
package='g4conf'
sh='/bin/sh'
sharpbang='#!'
shsharp='true'
spackage=''
spitshell='cat'
src='.'
startsh='#!/bin/sh'
CONFIG=true
